# Generated by Django 3.0.7 on 2020-12-11 15:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('death_count', models.IntegerField(default=0)),
                ('patient_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('pincode', models.IntegerField(primary_key=True, serialize=False)),
                ('hospital_count', models.IntegerField(default=0)),
                ('case_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='John Doe', max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('admission_date', models.DateTimeField(default=datetime.datetime.now)),
                ('discharge_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('test_status', models.CharField(max_length=3)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Quarantine_Info',
            fields=[
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Patient')),
                ('patient_name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('test_status', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='pincode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Locality'),
        ),
    ]
