# Generated by Django 3.0.7 on 2020-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='Gov hosp', max_length=256),
            preserve_default=False,
        ),
    ]
