# Generated by Django 3.0.7 on 2020-12-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201211_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discharge_date',
        ),
    ]
