# Generated by Django 3.0.7 on 2020-12-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201213_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarantine_info',
            name='patient_name',
        ),
    ]
