# Generated by Django 3.0.7 on 2020-12-22 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_quarantine_info_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='death_count',
        ),
    ]
